spring:
  application:
    name: task-buddy-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${DB_USER:appuser}
    password: ${DB_PASSWORD:apppassword}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

secret:
  jwt: ${SECRET:5f7eb49099eacde69a71f28ec55cd7b5b241b67b548de6903aa78123698bceba}
